<?php


    $Temp = Array
        (
            $_SERVER["SERVER_SOFTWARE"] = "Apache",
            $_SERVER["REQUEST_URI"] = "/karchidari-maintenance/",
            $_SERVER["REDIRECT_UNIQUE_ID"] = "W5PT9Coo5PaML0@yiOyx0QAAAAo",
            $_SERVER["REDIRECT_HTTPS"] = "on",
            $_SERVER["REDIRECT_SSL_TLS_SNI"] = "www.karchidari.com",
            $_SERVER["REDIRECT_STATUS"] = "200",
            $_SERVER["UNIQUE_ID"] = "W5PT9Coo5PaML0@yiOyx0QAAAAo",
            $_SERVER["HTTPS"] = "on",
            $_SERVER["SSL_TLS_SNI"] = "www.karchidari.com",
            $_SERVER["HTTP_HOST"] = "www.karchidari.com",
            $_SERVER["HTTP_CONNECTION"] = "keep-alive",
            $_SERVER["HTTP_CACHE_CONTROL"] = "max-age=0",
            $_SERVER["HTTP_UPGRADE_INSECURE_REQUESTS"] = "1",
            $_SERVER["HTTP_USER_AGENT"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
            $_SERVER["HTTP_ACCEPT"] = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
            $_SERVER["HTTP_REFERER"] = "https://www.karchidari.com/wp-admin/edit.php?post_type=page&amp;paged=2",
            $_SERVER["HTTP_ACCEPT_ENCODING"] = "gzip, deflate, br",
            $_SERVER["HTTP_ACCEPT_LANGUAGE"] = "en,en-GB;q=0.9,en-US;q=0.8",
            $_SERVER["HTTP_COOKIE"] = "wp-settings-2=libraryContent%3Dbrowse%26editor%3Dtinymce%26mfold%3Do%26edit_element_vcUIPanelWidth%3D650%26edit_element_vcUIPanelLeft%3D712px%26edit_element_vcUIPanelTop%3D74px; wp-settings-time-2=1536150753; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_19296fc68753757e82ae3736e668a91a=bijanbiria%7C1536556797%7C2rBUiUBK838hjulPvplZUXia0i7aJTuvbYBNgJnbt0o%7Cf9d92a0af2dcc93f7ff75a8f9c0d6a6e99b516021ff8181217b061ef47ae8053; clip-setting=%7B%22fixedHeader%22%3Atrue%2C%22fixedSidebar%22%3Atrue%2C%22closedSidebar%22%3Afalse%2C%22fixedFooter%22%3Afalse%2C%22theme%22%3A%22theme-1%22%7D",
            $_SERVER["PATH"] = "/sbin:/usr/sbin:/bin:/usr/bin",
            $_SERVER["SERVER_SIGNATURE"] = "",
            $_SERVER["SERVER_NAME"] = "www.karchidari.com",
            $_SERVER["SERVER_ADDR"] = "94.130.28.94",
            $_SERVER["SERVER_PORT"] = "443",
            $_SERVER["REMOTE_ADDR"] = "54.37.6.54",
            $_SERVER["DOCUMENT_ROOT"] = "/home/karchidari/domains/karchidari.com/private_html",
            $_SERVER["REQUEST_SCHEME"] = "https",
            $_SERVER["CONTEXT_PREFIX"] = "",
            $_SERVER["CONTEXT_DOCUMENT_ROOT"] = "/home/karchidari/domains/karchidari.com/private_html",
            $_SERVER["SERVER_ADMIN"] = "webmaster@karchidari.com",
            $_SERVER["SCRIPT_FILENAME"] = "/home/karchidari/domains/karchidari.com/private_html/index.php",
            $_SERVER["REMOTE_PORT"] = "51476";,
            $_SERVER["REDIRECT_URL"] = "/karchidari-maintenance/",
            $_SERVER["GATEWAY_INTERFACE"] = "CGI/1.1",
            $_SERVER["SERVER_PROTOCOL"] = "HTTP/1.1",
            $_SERVER["REQUEST_METHOD"] = "GET",
            $_SERVER["QUERY_STRING"] = "",
            $_SERVER["SCRIPT_NAME"] = "/index.php",
            $_SERVER["PHP_SELF"] = "/index.php",
            $_SERVER["REQUEST_TIME_FLOAT"] = "1536414708.025",
            $_SERVER["REQUEST_TIME"] = "1536414708"
        );
